import { useCallback, useEffect, useState } from 'react'
import { setUi } from '../sim/store.js'
import { presetHref, PRESETS } from '../sim/presets.js'

/**
 * The cosmic guide: what you see when the sim opens.
 *
 * A short, skippable tour that steers the *live* scene — the same camera the
 * simulator flies with — through the beats the product is made of, one caption
 * at a time. Nothing here is a video or a slideshow of renders: each step sets
 * the camera's focus and the scene responds, so the guide is the simulation
 * showing itself around.
 *
 * It opens once per browser (localStorage decides), stays reachable from the
 * front door, and gets out of the way with Esc or its own skip — an intro that
 * cannot be left is not an intro, it is a hostage situation.
 */

const STEPS = [
  {
    focus: 'sun',
    eyebrow: 'One star',
    title: 'The solar system, integrated live',
    body:
      'Everything you are about to see is computed, not drawn: eight bodies, one RK4 ' +
      'integrator, an ephemeris corrected for Earth\u2019s 23.01\u00b0 tilt. The planet on ' +
      'screen is where it actually is.',
  },
  {
    focus: 'earth',
    eyebrow: 'One planet',
    title: 'Earth, at true scale',
    body:
      'Real terrain heights under every pad, a PREM density model inside the planet, ' +
      'and a gravity field with its J\u2082\u2013J\u2084 harmonics \u2014 the oblateness that precesses ' +
      'every low orbit we fly.',
  },
  {
    focus: 'moon',
    eyebrow: 'One coast',
    title: 'The Moon, three days out',
    body:
      'Lunar terrain from LROC NAC and LOLA, and trajectories that are solved rather ' +
      'than aimed: multi-burn captures, halo orbits, and return corridors run in ' +
      'workers while you watch.',
  },
  {
    focus: 'ship',
    eyebrow: 'One vehicle',
    title: 'A hull you can stand next to',
    body:
      'Stages, umbilicals, swing arms and flame trenches modelled down to the pad \u2014 ' +
      'and acoustics synthesised live, so the rumble you hear is generated by the ' +
      'same engine that draws it.',
  },
  {
    focus: 'cinematic',
    eyebrow: 'Your turn',
    title: 'Fly one',
    body:
      'Nine flights, each flown from the pad when it loads. Pick the one you want to ' +
      'watch \u2014 or take the guided one from the pad, with the count at sixty.',
  },
]

const SEEN_KEY = 'periapsis.guide.v1'

export function guideShouldOpen() {
  try {
    return !window.localStorage.getItem(SEEN_KEY)
  } catch {
    return false
  }
}

export function Guide({ open, onClose, onLibrary }) {
  const [step, setStep] = useState(0)

  // Each beat points the live camera. One store write per step — the rig does
  // the flying.
  useEffect(() => {
    if (open) setUi({ focus: STEPS[step].focus })
  }, [open, step])

  const close = useCallback(() => {
    try {
      window.localStorage.setItem(SEEN_KEY, '1')
    } catch {
      /* private mode: the guide simply opens again next time */
    }
    onClose()
  }, [onClose])

  const next = useCallback(() => {
    setStep((s) => (s + 1 < STEPS.length ? s + 1 : s))
  }, [])
  const back = useCallback(() => setStep((s) => Math.max(0, s - 1)), [])

  useEffect(() => {
    if (!open) return
    const onKey = (e) => {
      if (e.key === 'Escape') {
        e.preventDefault()
        close()
      } else if (e.key === 'ArrowRight' || e.key === 'Enter' || e.key === ' ') {
        e.preventDefault()
        next()
      } else if (e.key === 'ArrowLeft') {
        e.preventDefault()
        back()
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open, close, next, back])

  if (!open) return null
  const s = STEPS[step]
  const last = step === STEPS.length - 1
  const launch = PRESETS.find((p) => p.id === 'apollo8-launch')

  return (
    <div className="pointer-events-none fixed inset-0 z-40 flex flex-col justify-between">
      {/* A vignette, so captions read against the scene whatever the camera is on. */}
      <div
        aria-hidden
        className="absolute inset-0"
        style={{
          background:
            'radial-gradient(120% 90% at 50% 40%, transparent 55%, rgba(10,11,13,0.55) 100%)',
        }}
      />

      {/* Top: the beat index, as a walkable rail of dots. */}
      <div className="pointer-events-auto flex items-start justify-between gap-6 px-6 pt-6 sm:px-10">
        <div className="flex items-center gap-3">
          <span className="font-mono text-[10px] tracking-[0.26em] text-hud/50 uppercase">
            A short tour
          </span>
          <div className="flex items-center gap-1.5" role="tablist" aria-label="Tour beats">
            {STEPS.map((st, i) => (
              <button
                key={st.title}
                role="tab"
                aria-selected={i === step}
                aria-label={st.eyebrow}
                onClick={() => setStep(i)}
                className={`h-px w-8 transition-colors duration-500 ${
                  i === step ? 'bg-ember' : i < step ? 'bg-hud/50' : 'bg-hud/20 hover:bg-hud/40'
                }`}
              />
            ))}
          </div>
          <span className="font-mono text-[10px] text-hud/40">
            {String(step + 1).padStart(2, '0')}/{String(STEPS.length).padStart(2, '0')}
          </span>
        </div>
        <button
          onClick={close}
          className="border border-hud/20 px-3 py-1.5 font-mono text-[10px] tracking-[0.22em] text-hud/70 uppercase transition-colors duration-300 hover:border-ember hover:text-ember"
        >
          Skip tour
        </button>
      </div>

      {/* Bottom: the caption card and its controls. */}
      <div className="pointer-events-auto px-6 pb-8 sm:px-10">
        <div className="mx-auto max-w-2xl border border-hud/15 bg-[#0a0b0d]/82 px-6 py-5 backdrop-blur-[3px]">
          <div className="font-mono text-[10px] tracking-[0.26em] text-ember/85 uppercase">
            {s.eyebrow}
          </div>
          <h2 className="mt-2 font-display text-2xl font-normal tracking-[0.03em] text-[#efe7db]">
            {s.title}
          </h2>
          <p className="mt-2.5 text-[12.5px] leading-relaxed text-[#e8e0d5]/72">{s.body}</p>

          <div className="mt-5 flex flex-wrap items-center gap-2">
            {last ? (
              <>
                <button
                  onClick={onLibrary}
                  className="border border-ember/70 px-4 py-2 font-mono text-[10px] tracking-[0.22em] text-ember uppercase transition-colors duration-300 hover:bg-ember/12"
                >
                  Open the mission library
                </button>
                <a
                  href={launch ? presetHref(launch) : '#flight'}
                  onClick={close}
                  className="border border-hud/25 px-4 py-2 font-mono text-[10px] tracking-[0.22em] text-hud/80 uppercase transition-colors duration-300 hover:border-ember hover:text-ember"
                >
                  Watch a launch from the pad
                </a>
              </>
            ) : (
              <>
                <button
                  onClick={next}
                  className="border border-hud/25 px-4 py-2 font-mono text-[10px] tracking-[0.22em] text-hud/85 uppercase transition-colors duration-300 hover:border-ember hover:text-ember"
                >
                  Next →
                </button>
                <button
                  onClick={back}
                  disabled={step === 0}
                  className="px-3 py-2 font-mono text-[10px] tracking-[0.22em] text-hud/55 uppercase transition-colors duration-300 hover:text-hud/85 disabled:opacity-35"
                >
                  ← Back
                </button>
              </>
            )}
            <span className="ml-auto font-mono text-[9px] tracking-[0.18em] text-hud/35 uppercase">
              ← → to walk · Esc to leave
            </span>
          </div>
        </div>
      </div>
    </div>
  )
}
