import { MARK } from '../gfx/brand.js'

/**
 * The mark, in React: the same geometry the favicon set, mark.svg and the
 * boot splash are drawn from — src/gfx/brand.js is generated by
 * scripts/make-favicon.mjs, so this cannot drift from the tab icon without
 * verify-icons going red.
 *
 * `plain` drops the obsidian tile: the HUD sits on the live sim, and a dark
 * square behind the lockup would print a box on the sky. The tile stays on
 * for the landing screen and the loading view, which stand on real surfaces.
 */
export function Mark({ size = 24, plain = true, className = '' }) {
  return (
    <svg
      viewBox={MARK.viewBox}
      width={size}
      height={size}
      className={className}
      role="img"
      aria-label="Periapsis Zero"
    >
      {plain ? null : <rect width="512" height="512" fill={MARK.ground} />}
      <path d={MARK.arc} fill="none" stroke={MARK.hud} strokeWidth={MARK.arcWidth} strokeLinecap="round" />
      {MARK.tick.map((d) => (
        <path key={d} d={d} fill="none" stroke={MARK.ember} strokeWidth={MARK.tickWidth} strokeLinecap="round" />
      ))}
      <circle cx={MARK.dot.cx} cy={MARK.dot.cy} r={MARK.dot.r} fill={MARK.hud} />
    </svg>
  )
}
