import { useState, useSyncExternalStore } from 'react'
import { CAMPAIGN, chapterUnlocked, expeditionRecord, REGIONS, subscribeExpeditions } from '../sim/expedition.js'

export function StoryCampaign({ onHome, onBegin }) {
  const record = useSyncExternalStore(subscribeExpeditions, expeditionRecord, expeditionRecord)
  const [selected, setSelected] = useState(() => CAMPAIGN.find((c) => !record.surveys[c.id]?.campaign)?.id ?? 'moon')
  const chapter = CAMPAIGN.find((c) => c.id === selected)
  const unlocked = chapterUnlocked(chapter.id, record), done = Boolean(record.surveys[chapter.id]?.campaign)
  return <main className="campaign-screen">
    <header className="mode-header"><button className="quiet-button" onClick={onHome}>← Home</button><span className="eyebrow">Periapsis Zero / Story</span><span className="eyebrow">{CAMPAIGN.filter((c) => record.surveys[c.id]?.campaign).length} of 3 done</span></header>
    <div className="campaign-layout">
      <aside className="chapter-list"><span className="eyebrow">Story</span><h1>Three<br />missions.</h1><p>One survey team, three worlds. Each mission unlocks the next.</p><nav aria-label="Campaign chapters">{CAMPAIGN.map((c) => <button key={c.id} className={`chapter-button ${selected === c.id ? 'selected' : ''}`} aria-current={selected === c.id ? 'step' : undefined} onClick={() => setSelected(c.id)}><span>{c.number}</span><div><strong>{c.title}</strong><small>{REGIONS[c.id].name} · {record.surveys[c.id]?.campaign ? 'Complete' : chapterUnlocked(c.id, record) ? 'Ready to fly' : 'Locked'}</small></div><span>{record.surveys[c.id]?.campaign ? '✓' : '↗'}</span></button>)}</nav><div className="campaign-save-note">Progress is saved in this browser.<br />Finish a mission to unlock the next one.</div></aside>
      <article className="chapter-dossier" key={chapter.id}><div className={`dossier-art ${chapter.id}${unlocked ? '' : ' locked'}`} aria-hidden><img src={`${import.meta.env.BASE_URL}stills/story-${chapter.id}.webp`} alt="" decoding="async" /><span>{chapter.number}</span></div><div className="dossier-content"><span className="eyebrow">{REGIONS[chapter.id].name} / {REGIONS[chapter.id].site}</span><h2>{chapter.title}</h2><div className="briefing-contact"><span className="contact-monogram">{chapter.contact.split(' ').map((n) => n[0]).join('')}</span><div><strong>{chapter.contact}</strong><small>{chapter.role}</small></div><span>Briefing</span></div><p className="briefing-text">{chapter.brief}</p><p className="briefing-stakes">{chapter.stakes}</p><ol className="briefing-objectives"><li><span>01</span>Land on the pad. Landing assist can fly it for you.</li><li><span>02</span>Collect the {chapter.samples[0].toLowerCase()} and the {chapter.samples[1].toLowerCase()}.</li><li><span>03</span>Drive the rover out and set up three instruments.</li><li><span>04</span>Bring everything back to the lander.</li></ol><div className="chapter-start"><button className="action-button primary" disabled={!unlocked} onClick={() => onBegin(chapter.id)}>{done ? 'Play again' : unlocked ? 'Start mission →' : 'Finish the previous mission first'}</button><span>About 10 minutes<br />Landing assist is optional</span></div><p className="fiction-note">A made-up near-future crew on generated terrain, with each world's real gravity. It is separate from the real historical missions in the Simulator.</p></div></article>
    </div>
  </main>
}
