import { useState, useSyncExternalStore } from 'react'
import { CAMPAIGN, chapterUnlocked, expeditionRecord, REGIONS, subscribeExpeditions } from '../sim/expedition.js'

export function StoryCampaign({ onHome, onBegin }) {
  const record = useSyncExternalStore(subscribeExpeditions, expeditionRecord, expeditionRecord)
  const [selected, setSelected] = useState(() => CAMPAIGN.find((c) => !record.surveys[c.id]?.campaign)?.id ?? 'moon')
  const chapter = CAMPAIGN.find((c) => c.id === selected)
  const unlocked = chapterUnlocked(chapter.id, record), done = Boolean(record.surveys[chapter.id]?.campaign)
  return <main className="campaign-screen">
    <header className="mode-header"><button className="quiet-button" onClick={onHome}>← Mode select</button><span className="eyebrow">Periapsis Zero / Story</span><span className="eyebrow">{CAMPAIGN.filter((c) => record.surveys[c.id]?.campaign).length} / 3 surveys</span></header>
    <div className="campaign-layout">
      <aside className="chapter-list"><span className="eyebrow">Survey division</span><h1>The ground<br />truth.</h1><p>A three-flight campaign about what orbit cannot tell you.</p><nav aria-label="Campaign chapters">{CAMPAIGN.map((c) => <button key={c.id} className={`chapter-button ${selected === c.id ? 'selected' : ''}`} aria-current={selected === c.id ? 'step' : undefined} onClick={() => setSelected(c.id)}><span>{c.number}</span><div><strong>{c.title}</strong><small>{REGIONS[c.id].name} · {record.surveys[c.id]?.campaign ? 'Complete' : chapterUnlocked(c.id, record) ? 'Ready to fly' : 'Locked'}</small></div><span>{record.surveys[c.id]?.campaign ? '✓' : '↗'}</span></button>)}</nav><div className="campaign-save-note">Progress stays in this browser.<br />Complete a survey to unlock the next flight.</div></aside>
      <article className="chapter-dossier" key={chapter.id}><div className={`dossier-art ${chapter.id}`} aria-hidden><span>{chapter.number}</span><div className="dossier-orbit" /></div><div className="dossier-content"><span className="eyebrow">{REGIONS[chapter.id].name} / {REGIONS[chapter.id].site}</span><h2>{chapter.title}</h2><div className="briefing-contact"><span className="contact-monogram">{chapter.contact.split(' ').map((n) => n[0]).join('')}</span><div><strong>{chapter.contact}</strong><small>{chapter.role}</small></div><span>Flight briefing</span></div><p className="briefing-text">{chapter.brief}</p><p className="briefing-stakes">{chapter.stakes}</p><ol className="briefing-objectives"><li><span>01</span>Land safely using assist or manual thrust.</li><li><span>02</span>Collect {chapter.samples[0].toLowerCase()} and {chapter.samples[1].toLowerCase()}.</li><li><span>03</span>Return both samples to the lander.</li></ol><div className="chapter-start"><button className="action-button primary" disabled={!unlocked} onClick={() => onBegin(chapter.id)}>{done ? 'Fly chapter again' : unlocked ? 'Begin chapter →' : 'Complete the previous survey'}</button><span>About 5–10 minutes<br />No orbital wait · assistance optional</span></div><p className="fiction-note">A fictional near-future crew. Procedural terrain, measured gravity. This campaign does not rewrite the historical flights in Simulator.</p></div></article>
    </div>
  </main>
}
