/**
 * Measures the simulated Moon's mean orbit and regenerates src/sim/moonMean.js.
 *
 * The Moon's rotation is locked to its orbit — Cassini's first law is that it
 * turns once per sidereal month, facing the *mean* Earth — so the frame it turns
 * in has to be phased and paced by the orbit it is actually on. That orbit is
 * the simulator's own, integrated from J2000 elements with the Sun and planets
 * pulling on it, and it is not quite the real Moon's: its elements are mean
 * values used as the osculating state, and the Sun's tide moves the osculating
 * semi-major axis by about a per cent either side of the mean, so the orbit
 * that results runs a sidereal month of 27.614 d against the real 27.322. A
 * frame paced by the real Moon drifted 3.8 degrees a month off the Moon it was
 * attached to.
 *
 * So the mean orbit is measured rather than looked up: a year of the integrated
 * system, sampled daily, and straight lines fitted through the unwrapped mean
 * longitude and the node of the osculating orbit. A year, because the largest
 * solar terms — evection at 31.8 days, the variation at 14.8, the annual
 * equation at a year — average out over it.
 *
 *   npm run moon:measure
 */
import { writeFileSync } from 'node:fs'

const { live } = await import('../src/sim/live.js')
const { INDEX } = await import('../src/sim/system.js')

const DAY = 86400
const OUT = 'src/sim/moonMean.js'
const DAYS = 365

/**
 * Integrate a year from J2000 and fit the mean orbit. Returns angles in
 * radians at J2000 and rates in radians per second.
 */
export function measureMoon(days = DAYS) {
  const t0 = live.sim.t
  // Geocentric state in the scene frame, and its ecliptic longitude and node.
  const sample = () => {
    const s = live.sim.state
    const m = INDEX.moon * 6
    const e = INDEX.earth * 6
    const r = [s[m] - s[e], s[m + 1] - s[e + 1], s[m + 2] - s[e + 2]]
    const v = [s[m + 3] - s[e + 3], s[m + 4] - s[e + 4], s[m + 5] - s[e + 5]]
    // Scene (x, y, z) is ecliptic (X, Z, -Y): longitude is atan2(Y, X).
    const lon = Math.atan2(-r[2], r[0])
    const h = [r[1] * v[2] - r[2] * v[1], r[2] * v[0] - r[0] * v[2], r[0] * v[1] - r[1] * v[0]]
    // The ascending node lies along (ecliptic north) x h; in ecliptic terms its
    // longitude is atan2(hX, -hY), with hX = h[0] and hY = -h[2].
    const node = Math.atan2(h[0], h[2])
    const hn = Math.hypot(h[0], h[1], h[2])
    const inc = Math.acos(h[1] / hn)
    return { lon, node, inc }
  }
  // The change from one sample's angle to the next, taken the short way round.
  const unwrap = (prev, next) => {
    let d = next - prev
    while (d > Math.PI) d -= 2 * Math.PI
    while (d < -Math.PI) d += 2 * Math.PI
    return d
  }
  let prev = sample()
  let lon = prev.lon
  let node = prev.node
  let inc = prev.inc
  const ts = [0]
  const lons = [lon]
  const nodes = [node]
  for (let d = 1; d <= days; d++) {
    live.sim.advance(DAY, 900)
    const s = sample()
    lon += unwrap(prev.lon, s.lon)
    node += unwrap(prev.node, s.node)
    inc += s.inc
    prev = s
    ts.push(live.sim.t - t0)
    lons.push(lon)
    nodes.push(node)
  }
  const fit = (xs, ys) => {
    const n = xs.length
    const mx = xs.reduce((a, b) => a + b) / n
    const my = ys.reduce((a, b) => a + b) / n
    let sxy = 0
    let sxx = 0
    for (let i = 0; i < n; i++) {
      sxy += (xs[i] - mx) * (ys[i] - my)
      sxx += (xs[i] - mx) ** 2
    }
    const slope = sxy / sxx
    return { at0: my - slope * mx, slope }
  }
  const L = fit(ts, lons)
  const N = fit(ts, nodes)
  const wrap = (a) => ((a % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI)
  return {
    longitude: wrap(L.at0),
    motion: L.slope,
    node: wrap(N.at0),
    nodeRate: N.slope,
    inclination: inc / (days + 1),
    days,
  }
}
if (import.meta.url === `file://${process.argv[1]}`) {
  const m = measureMoon()
  const deg = (r) => (r * 180) / Math.PI
  console.log(`mean longitude at J2000 ${deg(m.longitude).toFixed(4)}°, motion ${(deg(m.motion) * DAY).toFixed(6)}°/day`)
  console.log(`  sidereal month ${((2 * Math.PI) / m.motion / DAY).toFixed(4)} d (real 27.3217)`)
  console.log(`mean node at J2000 ${deg(m.node).toFixed(4)}°, regressing ${(deg(m.nodeRate) * DAY * 365.25).toFixed(3)}°/year`)
  console.log(`mean inclination ${deg(m.inclination).toFixed(4)}°`)
  writeFileSync(
    OUT,
    `// GENERATED by scripts/measure-moon.mjs — do not edit by hand.
// Re-run \`npm run moon:measure\` after changing the solar system's initial state.

/**
 * The simulated Moon's mean orbit, fitted over ${m.days} days of the integrated
 * system from J2000: angles at the epoch in radians, rates in radians per
 * second. The Moon's body-fixed frame (moonFrame.js) turns with it.
 */
export const MOON_MEAN = {
  longitude: ${m.longitude},
  motion: ${m.motion},
  node: ${m.node},
  nodeRate: ${m.nodeRate},
  inclination: ${m.inclination},
}
`,
  )
  console.log(`wrote ${OUT}`)
}
