/**
 * Measures the hull models that stand on a pad and regenerates
 * src/gfx/hullProfiles.js.
 *
 * The pad's swing arms reach to the vehicle at nine heights, so the pad has to
 * know how far out the vehicle is drawn at each — and when that vehicle is a
 * glTF, the only honest answer is the file. The model catalogue is not in the
 * repository (it is fetched at deploy), so the measurement is taken here, once,
 * from the file, and recorded as data the build and the gates can read without
 * it. `verify-pad-geometry` re-measures whenever the file is present and fails
 * if the record has drifted from it.
 *
 *   npm run hulls:measure
 */
import { existsSync, writeFileSync } from 'node:fs'
import { Matrix4, Object3D } from 'three'
import { glbTriangles, radiusProfile } from './glb.mjs'

process.env.PERIAPSIS_VESSEL ??= 'apollo8'
const { VESSELS } = await import('../src/sim/vessels.js')
const { MODEL_BY_ID } = await import('../src/gfx/modelsManifest.js')
const { noseOf, turnNose } = await import('../src/gfx/models.js')

/** Bands from tail to nose: 1% of the stack each, 1.1 m on a Saturn V. */
export const BINS = 100
const OUT = 'src/gfx/hullProfiles.js'

/** The profile of one catalogue model, turned as the craft turns it. */
export function measure(id) {
  const entry = MODEL_BY_ID[id]
  if (!entry) throw new Error(`no model "${id}" in the catalogue`)
  const file = `public/models/${decodeURIComponent(entry.file)}`
  if (!existsSync(file)) return null
  const { triangles, skipped } = glbTriangles(file)
  const turn = new Matrix4().makeRotationFromEuler(turnNose(new Object3D(), noseOf(id)).rotation)
  return { ...radiusProfile(triangles, turn, BINS), triangles: triangles.length / 9, skipped }
}

// Every model a vessel stands on its pad as.
const ids = [...new Set(Object.values(VESSELS).map((v) => v.stages?.[0]?.model).filter(Boolean))]

if (import.meta.url === `file://${process.argv[1]}`) {
  const profiles = {}
  for (const id of ids) {
    const m = measure(id)
    if (!m) {
      console.error(`${id}: file not present — fetch the model catalogue first`)
      process.exit(1)
    }
    profiles[id] = m.radius.map((x) => +x.toPrecision(6))
    console.log(`${id}: ${m.triangles} triangles (${m.skipped} primitives unreadable), ${BINS} bands`)
  }
  writeFileSync(
    OUT,
    `// GENERATED by scripts/measure-hulls.mjs — do not edit by hand.
// Re-run \`npm run hulls:measure\` after changing a model a vessel stands on its pad as.

/**
 * How far each such model stands out from its long axis, in ${BINS} equal bands
 * from its tail to its nose: the furthest any part of its surface reaches in
 * the band, as a fraction of the model's longest dimension — so, in metres, the
 * fraction times the length the hull is drawn at. Measured with the model
 * turned as the craft turns it (gfx/models.js).
 */
export const HULL_BINS = ${BINS}

/** @type {Record<string, number[]>} */
export const HULL_PROFILES = ${JSON.stringify(profiles)}
`,
  )
  console.log(`wrote ${OUT}`)
}
