/**
 * The brand gate: the mark is generated, this proves the generation held.
 *
 * The tab icon, mark.svg, src/gfx/brand.js and the index.html boot splash are
 * all drawn by scripts/make-favicon.mjs from one geometry and one palette.
 * That script's own `--check` compares every artefact byte-for-byte against a
 * fresh render — the strongest form of this test — so the gate runs it first
 * and fails with its output on any drift.
 *
 * What --check cannot see is whether index.html still *points* at the files.
 * A link edited by hand, a renamed asset, or a manifest entry nobody updated
 * leaves every generated byte intact while the tab shows the default globe
 * again. So the gate also resolves every icon URL the page and the manifest
 * name, and reads each file's magic bytes — not its HTTP status, because the
 * dev server's SPA fallback answers 200 with HTML for anything that looks
 * like a route, and an existence probe alone once shipped a wrong changelog
 * claim here. `\x89PNG` or the ICO header, or the gate is red.
 */

import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(here, '..')
let failures = 0
const fail = (msg) => {
  failures++
  console.log(`  FAIL  ${msg}`)
}
const pass = (msg) => console.log(`  ok    ${msg}`)

/* 1. The generated set is exactly what the drawing produces. */
const check = spawnSync(process.execPath, [join(here, 'make-favicon.mjs'), '--check'], {
  cwd: ROOT,
  stdio: ['ignore', 'pipe', 'inherit'],
})
console.log(check.stdout.toString().trimEnd())
if (check.status !== 0) fail('make-favicon --check: the set has drifted from the drawing')
else pass('make-favicon --check: all four surfaces byte-exact')

/* 2. Every icon URL the page names resolves to a real image. */
const html = readFileSync(join(ROOT, 'index.html'), 'utf8')
const hrefs = [...html.matchAll(/<link\s[^>]*href="([^"]+)"[^>]*>/g)]
  .map((m) => m[1])
  .filter((h) => h.startsWith('/icons/') || h === '/site.webmanifest')

const seen = new Set()
for (const href of hrefs) {
  if (seen.has(href)) continue
  seen.add(href)
  const file = join(ROOT, 'public', href)
  let bytes = null
  try {
    bytes = readFileSync(file)
  } catch {
    fail(`${href}: referenced by index.html but missing on disk`)
    continue
  }
  if (href.endsWith('.png')) {
    const png = bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47
    if (!png) fail(`${href}: exists but is not a PNG (SPA fallback shipped something else?)`)
    else pass(`${href} → PNG, ${bytes.length} B`)
  } else if (href.endsWith('.ico')) {
    const ico = bytes[0] === 0 && bytes[1] === 0 && bytes[2] === 1 && bytes[3] === 0
    if (!ico) fail(`${href}: exists but is not an ICO`)
    else pass(`${href} → ICO, ${bytes.length} B`)
  } else {
    pass(`${href} → ${bytes.length} B`)
  }
}

/* 3. The manifest's own icon entries. */
try {
  const manifest = JSON.parse(readFileSync(join(ROOT, 'public/site.webmanifest'), 'utf8'))
  for (const icon of manifest.icons ?? []) {
    const file = join(ROOT, 'public', icon.src)
    try {
      const bytes = readFileSync(file)
      const png = bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47
      if (!png) fail(`manifest icon ${icon.src}: not a PNG`)
      else pass(`manifest ${icon.src} (${icon.sizes}) → PNG, ${bytes.length} B`)
    } catch {
      fail(`manifest icon ${icon.src}: missing on disk`)
    }
  }
} catch (e) {
  fail(`site.webmanifest unreadable: ${e.message}`)
}

/* 4. brand.js is importable and carries one arc, two tick strokes, one dot. */
try {
  const { MARK } = await import(join(ROOT, 'src/gfx/brand.js'))
  const oneArc = typeof MARK.arc === 'string' && MARK.arc.startsWith('M ') && MARK.arc.includes('Q ')
  const twoTicks = Array.isArray(MARK.tick) && MARK.tick.length === 2
  const dot = MARK.dot && MARK.dot.r > 0
  if (oneArc && twoTicks && dot) pass(`brand.js imports clean (arc, 2 ticks, dot r=${MARK.dot.r})`)
  else fail(`brand.js shape wrong: arc=${oneArc} ticks=${twoTicks} dot=${dot}`)
} catch (e) {
  fail(`brand.js does not import: ${e.message}`)
}

/* 5. The splash block is present exactly once. */
const opens = html.split('<!-- boot:generated').length - 1
const closes = html.split('<!-- /boot:generated -->').length - 1
if (opens === 1 && closes === 1) pass('index.html boot splash present, markers balanced')
else fail(`boot splash markers: ${opens} opens, ${closes} closes (want 1 and 1)`)

console.log(failures ? `\n  ${failures} failure${failures === 1 ? '' : 's'}` : '\n  PASS')
process.exit(failures ? 1 : 0)
