// GENERATED by scripts/measure-moon.mjs — do not edit by hand.
// Re-run `npm run moon:measure` after changing the solar system's initial state.

/**
 * The simulated Moon's mean orbit, fitted over 365 days of the integrated
 * system from J2000: angles at the epoch in radians, rates in radians per
 * second. The Moon's body-fixed frame (moonFrame.js) turns with it.
 */
export const MOON_MEAN = {
  longitude: 3.784351146364365,
  motion: 0.000002633547736560065,
  node: 2.2067253030281044,
  nodeRate: -1.1132188392395287e-8,
  inclination: 0.08849337524847074,
}
