// GENERATED by scripts/measure-moon.mjs — do not edit by hand.
// Re-run `npm run moon:measure` after changing the solar system's initial state.

/**
 * The simulated Moon's mean orbit, fitted over 365 days of the integrated
 * system from J2000: angles at the epoch in radians, rates in radians per
 * second. The Moon's body-fixed frame (moonFrame.js) turns with it.
 */
export const MOON_MEAN = {
  longitude: 3.7838489206528507,
  motion: 0.000002635042294653017,
  node: 2.2070386246601057,
  nodeRate: -1.111296414566219e-8,
  inclination: 0.0885752966532254,
}
