// GENERATED by scripts/measure-moon.mjs — do not edit by hand.
// Re-run `npm run moon:measure` after changing the solar system's initial state.

/**
 * The simulated Moon's mean orbit, fitted over 365 days of the integrated
 * system from J2000: angles at the epoch in radians, rates in radians per
 * second. The Moon's body-fixed frame (moonFrame.js) turns with it.
 */
export const MOON_MEAN = {
  longitude: 3.8011096401337454,
  motion: 0.000002660361722156184,
  node: 2.186271944454191,
  nodeRate: -1.1029419609020958e-8,
  inclination: 0.09005086334972301,
}
