// Generated by scripts/make-favicon.mjs — the mark's geometry and palette as
// code, the single source the favicon set, mark.svg and the boot splash are
// all drawn from. Edit the drawing there and re-run `npm run icons`; do not
// edit this file, and do not restate its colours anywhere.

export const MARK = {
  viewBox: '0 0 512 512',
  ground: '#080a0d',
  hud: '#d5c6a1',
  ember: '#d7733e',
  arc: 'M -143.36 92.16 Q 256 645.12 655.36 92.16',
  tick: [
    'M 256 400.38 L 199.68 451.07',
    'M 256 400.38 L 312.32 451.07',
  ],
  dot: { cx: 256, cy: 368.64, r: 29.7 },
  arcWidth: 15.36,
  tickWidth: 19.46,
}
