// Generated by scripts/make-favicon.mjs — the mark's geometry and palette as
// code, the single source the favicon set, mark.svg and the boot splash are
// all drawn from. Edit the drawing there and re-run `npm run icons`; do not
// edit this file, and do not restate its colours anywhere.

export const MARK = {
  viewBox: '0 0 512 512',
  ground: '#120b22',
  hud: '#f4e8cf',
  ember: '#ff6b2c',
  // The planet's gradient: lit upper-left, night side toward the ground.
  tint: '#f6edda',
  mid: '#a59b92',
  night: '#322a3a',
  planet: { cx: 256, cy: 256, r: 104.96 },
  orbit: { cx: 256, cy: 240.64, a: 197.12, b: 117.76 },
  orbitFar: 'M 58.88 240.64 A 197.12 117.76 0 0 1 453.12 240.64',
  orbitNear: 'M 58.88 240.64 A 197.12 117.76 0 0 0 453.12 240.64',
  orbitFarWidth: 13.31,
  orbitNearWidth: 19.46,
  periapsis: { cx: 256, cy: 358.4, r: 22.53 },
  tick: [
    'M 256 404.48 L 212.48 443.65',
    'M 256 404.48 L 299.52 443.65',
  ],
  tickWidth: 16.38,
  // [x, y, radius, opacity] at the 512 reference size.
  stars: [[74.24, 79.36, 2.6, 0.75], [432.64, 58.88, 1.9, 0.6], [463.36, 174.08, 2.3, 0.7], [43.52, 192, 1.7, 0.5], [368.64, 448, 2, 0.55], [94.72, 440.32, 1.6, 0.5]],
}
