// GENERATED by scripts/scan-models.mjs — do not edit by hand.
// Re-run `npm run models:scan` after adding or removing files in public/models/.
//
// 48 loadable models, 140 MB total.
// Paths are URL-encoded per segment: NASA's folder names contain spaces and
// parentheses, and an unencoded request for them fails outright.

/** @typedef {{id: string, label: string, group: string, file: string, bytes: number}} ModelEntry */

/** @type {ModelEntry[]} */
export const MODEL_CATALOG = [
  {
    "id": "fermi",
    "label": "Fermi Gamma-ray Telescope",
    "group": "Observatories",
    "file": "Fermi%20Gamma-ray%20Large%20Area%20Space%20Telescope/Fermi%20Gamma-ray%20Large%20Area%20Space%20Telescope.glb",
    "bytes": 1379016
  },
  {
    "id": "hubble",
    "label": "Hubble Space Telescope",
    "group": "Observatories",
    "file": "Hubble%20Space%20Telescope%20(A)/hubble.glb",
    "bytes": 1694988
  },
  {
    "id": "jwst",
    "label": "James Webb Space Telescope",
    "group": "Observatories",
    "file": "James%20Webb%20Space%20Telescope%20(A)/James%20Webb%20Space%20Telescope%20(A).glb",
    "bytes": 4710016
  },
  {
    "id": "kepler",
    "label": "Kepler",
    "group": "Observatories",
    "file": "Kepler%20(A)/Kepler%20(A).glb",
    "bytes": 2003276
  },
  {
    "id": "roman",
    "label": "Nancy Grace Roman Telescope",
    "group": "Observatories",
    "file": "Nancy%20Grace%20Roman%20Space%20Telescope%20(A)/Nancy%20Grace%20Roman%20Space%20Telescope%20(A).glb",
    "bytes": 2672000
  },
  {
    "id": "apollo_lm",
    "label": "Apollo Lunar Module",
    "group": "Crewed",
    "file": "Apollo%20Lunar%20Module.glb",
    "bytes": 716840
  },
  {
    "id": "apollo_csm",
    "label": "Apollo–Soyuz",
    "group": "Crewed",
    "file": "Apollo%20Soyuz/apollo_csm.glb",
    "bytes": 952608
  },
  {
    "id": "gateway",
    "label": "Gateway Core",
    "group": "Crewed",
    "file": "Gateway/Gateway%20Core.glb",
    "bytes": 66214552
  },
  {
    "id": "gemini",
    "label": "Gemini",
    "group": "Crewed",
    "file": "Gemini/Gemini.glb",
    "bytes": 1387812
  },
  {
    "id": "shuttle",
    "label": "Space Shuttle",
    "group": "Crewed",
    "file": "Space%20Shuttle%20(A)/Space%20Shuttle%20(A).glb",
    "bytes": 1194068
  },
  {
    "id": "cassini",
    "label": "Cassini-Huygens",
    "group": "Deep space",
    "file": "Cassini-Huygens%20(A)/Cassini-Huygens%20(A).glb",
    "bytes": 1660492
  },
  {
    "id": "deepspace1",
    "label": "Deep Space 1",
    "group": "Deep space",
    "file": "Deep%20Space%201/Deep%20Space%201.glb",
    "bytes": 934676
  },
  {
    "id": "juno",
    "label": "Juno",
    "group": "Deep space",
    "file": "Juno%20(A)/Juno%20(A).glb",
    "bytes": 8999028
  },
  {
    "id": "parker",
    "label": "Parker Solar Probe",
    "group": "Deep space",
    "file": "Parker%20Solar%20Probe/Parker%20Solar%20Probe.glb",
    "bytes": 443572
  },
  {
    "id": "voyager",
    "label": "Voyager Probe",
    "group": "Deep space",
    "file": "Voyager%20Probe%20(A)/Voyager%20Probe%20(A).glb",
    "bytes": 285936
  },
  {
    "id": "saturn_v",
    "label": "Saturn V",
    "group": "Launch vehicles",
    "file": "Saturn%20V/Saturn%20V.glb",
    "bytes": 927212
  },
  {
    "id": "odyssey",
    "label": "Mars Odyssey",
    "group": "Planetary",
    "file": "Mars%20Odyssey/Mars%20Odyssey.glb",
    "bytes": 5801372
  },
  {
    "id": "perseverance",
    "label": "Perseverance Rover",
    "group": "Planetary",
    "file": "Mars%202020%20Perseverance%20Rover/Mars%202020%20Perseverance%20Rover.glb",
    "bytes": 4987176
  },
  {
    "id": "aura",
    "label": "Aura",
    "group": "Earth science",
    "file": "Aura%20(A)/Aura%20(A).glb",
    "bytes": 476264
  },
  {
    "id": "bennu",
    "label": "Bennu (101955)",
    "group": "Small bodies",
    "file": "1999%20RQ36%20asteroid/1999%20RQ36%20asteroid.glb",
    "bytes": 329596
  },
  {
    "id": "space_shuttle_parts_eva_suit",
    "label": "EVA suit",
    "group": "Shuttle parts",
    "file": "Space%20Shuttle%20Parts/EVA%20suit.glb",
    "bytes": 715864
  },
  {
    "id": "space_shuttle_parts_external_tank",
    "label": "External tank",
    "group": "Shuttle parts",
    "file": "Space%20Shuttle%20Parts/External%20tank.glb",
    "bytes": 848352
  },
  {
    "id": "space_shuttle_parts_orbiter_docking_system",
    "label": "Orbiter Docking System",
    "group": "Shuttle parts",
    "file": "Space%20Shuttle%20Parts/Orbiter%20Docking%20System.glb",
    "bytes": 841040
  },
  {
    "id": "space_shuttle_parts_payload",
    "label": "Payload",
    "group": "Shuttle parts",
    "file": "Space%20Shuttle%20Parts/Payload.glb",
    "bytes": 516016
  },
  {
    "id": "space_shuttle_parts_solid_rocket_booster",
    "label": "Solid Rocket Booster",
    "group": "Shuttle parts",
    "file": "Space%20Shuttle%20Parts/Solid%20Rocket%20Booster.glb",
    "bytes": 2665460
  },
  {
    "id": "space_shuttle_remote_manipulator_system_canadarm_space_shuttle_remote_manipulator_system_canadarm",
    "label": "Space Shuttle Remote Manipulator System (Canadarm)",
    "group": "Shuttle parts",
    "file": "Space%20Shuttle%20Remote%20Manipulator%20System%20(Canadarm)/Space%20Shuttle%20Remote%20Manipulator%20System%20(Canadarm).glb",
    "bytes": 271276
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_al_al_ext",
    "label": "al-ext",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/al/al-ext.glb",
    "bytes": 3054720
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_ams_ams2",
    "label": "AMS2",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/ams/AMS2.glb",
    "bytes": 1504608
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_atv_atv_temp",
    "label": "ATV_temp",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/atv/ATV_temp.glb",
    "bytes": 790180
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_columbus_columbus",
    "label": "columbus",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/columbus/columbus.glb",
    "bytes": 973584
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_cupola_cupola_open",
    "label": "cupola_open",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/cupola/cupola_open.glb",
    "bytes": 2134096
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_express_elc_elc1",
    "label": "ELC1",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/express%20ELC/ELC1.glb",
    "bytes": 1015212
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_express_elc_elc2",
    "label": "ELC2",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/express%20ELC/ELC2.glb",
    "bytes": 1425176
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_express_elc_elc3",
    "label": "ELC3",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/express%20ELC/ELC3.glb",
    "bytes": 1589056
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_express_elc_elc4",
    "label": "ELC4",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/express%20ELC/ELC4.glb",
    "bytes": 1304092
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_esp1_esp1",
    "label": "ESP1",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/esp1/ESP1.glb",
    "bytes": 188432
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_esp2_esp2_lo",
    "label": "esp2_lo",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/esp2/esp2_lo.glb",
    "bytes": 358988
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_esp3_esp3",
    "label": "ESP3",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/esp3/ESP3.glb",
    "bytes": 757852
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_fgb_fgb_ext",
    "label": "fgb-ext",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/fgb/fgb-ext.glb",
    "bytes": 4089600
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_fgb_fgb_ext_closed",
    "label": "fgb-ext_closed",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/fgb/fgb-ext_closed.glb",
    "bytes": 3971880
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_fgb_fgb_ext_layers",
    "label": "fgb-ext_layers",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/fgb/fgb-ext_layers.glb",
    "bytes": 4089600
  },
  {
    "id": "international_space_station_iss_c_high_res_objects_modules_htv_htv_temp",
    "label": "HTV_temp",
    "group": "ISS modules",
    "file": "International%20Space%20Station%20(ISS)%20(C)%20(High%20Res)/Objects/Modules/htv/HTV_temp.glb",
    "bytes": 472504
  },
  {
    "id": "cassini_huygens_a_cassini_huygens_a_without_cassini",
    "label": "Cassini-Huygens (A) (without Cassini)",
    "group": "Other",
    "file": "Cassini-Huygens%20(A)/Cassini-Huygens%20(A)%20(without%20Cassini).glb",
    "bytes": 1014092
  },
  {
    "id": "cassini_huygens_a_cassini_huygens_a_without_hyugens",
    "label": "Cassini-Huygens (A) (without Hyugens)",
    "group": "Other",
    "file": "Cassini-Huygens%20(A)/Cassini-Huygens%20(A)%20(without%20Hyugens).glb",
    "bytes": 1653316
  },
  {
    "id": "cassini_huygens_b_cassini_huygens_b",
    "label": "Cassini-Huygens (B)",
    "group": "Other",
    "file": "Cassini-Huygens%20(B)/Cassini-Huygens%20(B).glb",
    "bytes": 413640
  },
  {
    "id": "juno_b_juno_b",
    "label": "Juno (B)",
    "group": "Other",
    "file": "Juno%20(B)/Juno%20(B).glb",
    "bytes": 262360
  },
  {
    "id": "voyager_probe_b_voyager_probe_b",
    "label": "Voyager Probe (B)",
    "group": "Other",
    "file": "Voyager%20Probe%20(B)/Voyager%20Probe%20(B).glb",
    "bytes": 1720864
  },
  {
    "id": "voyager_probe_b_voyager_probe_b_antenna",
    "label": "Voyager Probe (B) (antenna)",
    "group": "Other",
    "file": "Voyager%20Probe%20(B)/Voyager%20Probe%20(B)%20(antenna).glb",
    "bytes": 166352
  }
]

export const MODEL_GROUPS = [
  "Observatories",
  "Crewed",
  "Deep space",
  "Launch vehicles",
  "Planetary",
  "Earth science",
  "Small bodies",
  "Shuttle parts",
  "ISS modules",
  "Other"
]

export const MODEL_BY_ID = Object.fromEntries(MODEL_CATALOG.map((m) => [m.id, m]))

/** Assigned to each craft on first load, when the file is present. */
export const DEFAULT_ASSIGNMENT = {
  ship: 'apollo_csm',
  hubble: 'hubble',
  iss: null,
}
